# Generated by Django 5.2.7 on 2025-10-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_title', models.CharField(max_length=200)),
                ('due_date', models.DateTimeField()),
                ('weight_percent', models.FloatField(default=0.0)),
            ],
        ),
    ]
