# Generated by Django 5.2.7 on 2025-10-28 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Syllabus',
            new_name='Deadline',
        ),
    ]
