# Generated by Django 5.2.7 on 2025-10-29 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_rename_syllabus_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='deadline',
            name='syllabus',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='parser.syllabus'),
            preserve_default=False,
        ),
    ]
