# Generated by Django 5.2.7 on 2025-10-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0003_syllabus_deadline_syllabus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='due_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
