# Generated by Django 5.2.7 on 2025-11-05 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0005_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=7)),
                ('prof_email', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='deadline',
            old_name='assignment_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='deadline',
            old_name='weight_percent',
            new_name='weight',
        ),
        migrations.RemoveField(
            model_name='deadline',
            name='syllabus',
        ),
        migrations.AddField(
            model_name='syllabus',
            name='file',
            field=models.FileField(null=True, upload_to='syllabi/'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='hash',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deadline',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='parser.course'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='class_template',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parser.course'),
        ),
        migrations.CreateModel(
            name='PolicyPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField(default=0.0)),
                ('penalty', models.FloatField(default=0.0)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='late_policy', to='parser.course')),
            ],
        ),
    ]
