# Generated by Django 5.2.7 on 2025-11-06 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0009_alter_syllabus_class_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='class_template',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='syllabus', to='parser.course'),
        ),
    ]
